#!/bin/bash

echo "== deploy ecs ec2"

STACK_NAME="ecs-ecs2-cp"

aws cloudformation deploy \
--template-file capacity-provider.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region us-east-1 \
--stack-name $STACK_NAME
