#!/bin/bash

# use full binaries path in scripts
[[ -n "$DEVPOD_WORKSPACE_ID" ]] && /usr/local/bin/mise trust /workspaces/$DEVPOD_WORKSPACE_ID/mise.toml && /usr/local/bin/mise install
[[ -n "$DEVSY_WORKSPACE_ID" ]] && /usr/local/bin/mise trust /workspaces/$DEVSY_WORKSPACE_ID/mise.toml && /usr/local/bin/mise install
