#!/bin/bash

echo "== deploy ecs fargate"

STACK_NAME="ecs-fargate-basic"

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region us-east-1 \
--stack-name $STACK_NAME
