#!/bin/bash
ARRAY=( 'Debian Linux', 'Redhat Linux', Ubuntu, Linux)
# get number of elements in the array
ELEMENTS=${#ARRAY[@]}

# echo each elements in the array
for (( i=0;i<$ELEMENTS;i++)); do
  echo ${ARRAY[i]}
done
