#!/bin/bash

# bash trap command for interrupt
trap bashtrap INT
clear;

# bash trap function is executed when CTRL-C is pressed:
# bash prints message => Executing bash trap subroutine

bashtrap() {
  echo "CTRL+C detected! ...executing bash trap!"
}

for a in `seq 1 10`; do
  echo "$a/10 to Exit."
  sleep 1;
done

echo "Exit bash trap example"
