#!/bin/bash

# to do would be adding input validation

# check that 2 arguments are passed
if [ $# -ne 2 ]; then
  echo "Usage: $0 <num1> <num2>"
  exit 1
fi

if ! [[ $1 =~ ^[0-9]+$ ]] || ! [[ $2 =~ ^[0-9]+$ ]]; then
  echo "Error: input values must be integers"
  exit 1
fi

NUM1=$1
NUM2=$2
if [ $NUM1 -eq $NUM2 ]; then
  echo "Both values are equal"
elif [ $NUM1 -gt $NUM2 ]; then
  echo "$NUM1 is greater than $NUM2"
else
  echo "$NUM1 is less than $NUM2"
fi
