#!/bin/bash
# Bash functions can be declared in any order
function function_B {
  echo Function B.
}

function function_A {
  echo $1
}

function function_D {
  echo Function D.
}

function function_C {
  echo $1
}

# FUNCTION CALLS
# Pass parameter to function A
function_A "Hello"
function_B
# Pass parameter to function C
function_C "World"
function_D
